### ISSUE TITLE
버그 제보요 

### ISSUE THREAD

**Issue by MadeGOD** [wonderlandpark/dokdo#28]
```cmd
/home/madegod/꿀꿀봇/node_modules/dokdo/src/index.js:39
0|pigbog  |     if (!(client instanceof Discord.Client)) throw new Error('Invalid `client`. `client` parameter is required.')
0|pigbog  |                                              ^
0|pigbog  | Error: Invalid `client`. `client` parameter is required.
0|pigbog  |     at new Dokdo (/home/madegod/꿀꿀봇/node_modules/dokdo/src/index.js:39:52)
0|pigbog  |     at Object.<anonymous> (/home/madegod/꿀꿀봇/bot.js:14:15)
0|pigbog  |     at Module._compile (internal/modules/cjs/loader.js:1063:30)
0|pigbog  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
0|pigbog  |     at Module.load (internal/modules/cjs/loader.js:928:32)
0|pigbog  |     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
0|pigbog  |     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
0|pigbog  |     at internal/main/run_main_module.js:17:47
```
해당 버그입니다. 아무런 문제가 없다가 갑자기 뜨는데요?
해결방법이나 재현을 해주시길 바랍니다

**Comment by wonderlandpark** [comment]
코드도 첨부해주실 수 있나요?

**Comment by MadeGOD** [comment]
const dokdo = new(require('dokdo'))(client, {prefix: ',,'}); 
client.on('message', dokdo.run.bind(dokdo))
