### ISSUE TITLE
[BUG] Error: Expected a string, got $ ls, instead.

### ISSUE THREAD

**Issue by zero734kr** [wonderlandpark/dokdo#400]
### Please explain the bug!

I ran `.dok sh ls` on my bot with new discord.js v13, but instead of producing the output, an error occurred.

### Relevant log output

```shell
Error: Expected a string, got $ ls, instead.
    at Function.verifyString (/media/zero/ohmyEFD/codes/lostark-rwt/node_modules/discord.js/src/util/Util.js:417:41)
    at Function.splitMessage (/media/zero/ohmyEFD/codes/lostark-rwt/node_modules/discord.js/src/util/Util.js:77:17)
    at ProcessManager.splitContent (/media/zero/ohmyEFD/codes/lostark-rwt/node_modules/dokdo/src/utils/ProcessManager.js:180:25)
    at new ProcessManager (/media/zero/ohmyEFD/codes/lostark-rwt/node_modules/dokdo/src/utils/ProcessManager.js:48:26)
    at Object.Exec [as exec] (/media/zero/ohmyEFD/codes/lostark-rwt/node_modules/dokdo/src/commands/exec.js:11:15)
    at Dokdo.run (/media/zero/ohmyEFD/codes/lostark-rwt/node_modules/dokdo/src/index.js:113:18)
    at MessageCreate.run (/media/zero/ohmyEFD/codes/lostark-rwt/src/events/messageCreate.js:21:28)
    at LostArk.<anonymous> (/media/zero/ohmyEFD/codes/lostark-rwt/src/client/client.js:258:57)
    at LostArk.emit (node:events:390:28)
    at LostArk.emit (node:domain:475:12)
```

### What steps do you need to take to make this bug reproduced?

- Step 1. 
Install discord.js v13

- Step 2. 
Make a bot with it and use ``dokdo`` for debugging

- Step 3. 
Run ``<prefix>.dok sh ls`` in Discord

### Dokdo Version

v0.3.0

### Node.js / Discord.js Version

v16.13.2 / v13.6.0

**Comment by wonderlandpark** [comment]
Is this bug still reproducible?

**Comment by wonderlandpark** [comment]
Closing Issue. (seems like its non-reproducible.)
